/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersCreationMonthsImport } from './routes/users/creation-months'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersCreationMonthsRoute = UsersCreationMonthsImport.update({
  path: '/users/creation-months',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/users/creation-months': {
      id: '/users/creation-months'
      path: '/users/creation-months'
      fullPath: '/users/creation-months'
      preLoaderRoute: typeof UsersCreationMonthsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users/creation-months': typeof UsersCreationMonthsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users/creation-months': typeof UsersCreationMonthsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/users/creation-months': typeof UsersCreationMonthsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/users/creation-months'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/users/creation-months'
  id: '__root__' | '/' | '/users/creation-months'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersCreationMonthsRoute: typeof UsersCreationMonthsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersCreationMonthsRoute: UsersCreationMonthsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/users/creation-months"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/users/creation-months": {
      "filePath": "users/creation-months.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
